spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kindergarten
    username: postgres
    password: your_password
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect